#!/bin/bash

# Find the latest tag of an image on local disk,
# assuming tags are sortable.
# The sole input is the name of the image, with repository as needed,
# e.g.
#     debian
#     zppz/py3

set -e

NAME="$1"


function find-latest-local-image {
    if [[ "${NAME}" == *:* ]]; then
        if [ $(docker images -q "${NAME}") ]; then
            # Exists locally.
            echo "${NAME}"
        fi
        return 0
    fi

    tags=$(docker image ls ${NAME} --format "{{.Tag}}")
    if [ -z "${tags}" ]; then
        return 0
    fi

    if [[ $(echo "${tags}" |grep latest) == latest ]]; then
        echo "${NAME}:latest"
        return 0
    fi

    tag=$(echo "${tags}" |sort |tail -n 1)
    echo "${NAME}:${tag}"
}

tag=$(find-latest-local-image)
if [ "${tag}" ]; then
    echo "${tag}"
    exit 0
else
    >&2 echo could not find image "${NAME}" locally
    exit 1
fi
